
name: smart_water_tank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  liquid_progress_indicator_v2: ^0.5.0
  firebase_auth: ^4.19.5
  firebase_core: ^2.32.0
  firebase_database: ^10.5.5
  firebase_messaging: ^14.9.4
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  connectivity_plus: ^7.0.0
  flutter_blue_plus: ^1.31.15
  permission_handler: ^11.3.1
  cloud_functions: ^4.6.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21